import json
from typing import Any, Dict

# System Prompt remains the same
SYSTEM_PROMPT = """
Validate SAR reports against FinCEN requirements

- Check required fields and format compliance
- Verify WHO, WHAT, WHEN, WHERE, WHY, HOW elements
- Flag missing or inconsistent information
- Assess narrative quality
- Evaluate supporting evidence
- Assign compliance score (0-100)
- Set verification status: approved, needs_revision, rejected
- Identify issues by section, type, severity
- Provide recommendations for corrections

JSON OUTPUT SCHEMA:
{
    "verification_result": {
        "report_id": "string",
        "verification_timestamp": "string (ISO 8601 date-time format)",
        "is_compliant": "boolean",
        "compliance_score": "number (optional)",
        "verification_status": "string (approved, needs_revision, rejected)",
        "ready_for_submission": "boolean"
    },
    "fincen_requirements": {
        "required_fields_present": "boolean",
        "format_compliance": "boolean",
        "narrative_quality": "string (excellent, good, adequate, inadequate)",
        "supporting_evidence_sufficient": "boolean (optional)"
    },
    "issues": [
        {
            "section": "string",
            "issue_type": "string (missing_information, format_error, inconsistency, insufficient_detail)",
            "description": "string",
            "severity": "string (critical, major, minor)",
            "recommendation": "string (optional)"
        }
    ],
    "llm_verification": {
        "completeness_assessment": "string",
        "accuracy_assessment": "string",
        "consistency_check": "string (optional)",
        "overall_quality": "string (excellent, good, adequate, inadequate)"
    },
    "verification_summary": "string"
}
"""

class ComplianceVerificationAgent:
    """
    Agent for verifying SAR report compliance with FinCEN requirements using an LLM.
    (Simplified: No BaseAgent inheritance)
    """

    def __init__(self, client):
        """Initialize the agent.

        Args:
            client: OpenAI client instance.
        """
        self.client = client

    def _format_input(self, input_data: Any) -> str:
        """Format the input data for the API."""
        if isinstance(input_data, dict):
            return json.dumps(input_data)
        return str(input_data)

    def _call_api(self, user_content_str: str) -> Any:
        """Call the OpenAI Responses API."""
         # Simple check to suggest JSON format if not obviously present
        if "json" not in user_content_str.lower():
             user_content_str = f"{user_content_str}\nPlease provide the response in JSON format."

        response = self.client.responses.create(
            model='o3-mini-2025-01-31',
            instructions=SYSTEM_PROMPT,
            input=user_content_str,
            text={"format": {"type": "json_object"}},
            reasoning={"effort": "high"},
            tools=[],
            store=True
        )
        return response

    def _parse_response(self, response: Any) -> Dict[str, Any]:
        """Extract and parse the JSON response content."""
        if response.status != "completed":
            error_msg = f"Response status: {response.status}"
            if response.error:
                error_msg = f"API Error: {response.error}"
            elif response.incomplete_details:
                error_msg = f"Incomplete response: {response.incomplete_details}"
            raise Exception(error_msg)

        if not response.output or len(response.output) == 0:
            raise Exception("No output items returned from the API")

        for item in response.output:
            if hasattr(item, 'type') and item.type == "message":
                if hasattr(item, 'content') and item.content and len(item.content) > 0:
                    content_block = item.content[0]
                    if hasattr(content_block, 'text'):
                        raw_text = content_block.text
                        try:
                            return json.loads(raw_text)
                        except json.JSONDecodeError as e:
                             raise Exception(f"Failed to parse JSON response: {e}\nRaw text: {raw_text}")

        raise Exception("No message-type output items found in response")

    def run(self, sar_report: Dict[str, Any]) -> Dict[str, Any]:
        """
        Verify SAR report compliance against FinCEN requirements.

        Args:
            sar_report: SAR report generated by the SAR Generation Agent.

        Returns:
            Verification results with compliance assessment and issues.
        """
        formatted_input = self._format_input(sar_report)
        api_response = self._call_api(formatted_input)
        parsed_response = self._parse_response(api_response)
        return parsed_response