from agents.base_agent import BaseAgent
SYSTEM_PROMPT = """
Validate SAR reports against FinCEN requirements

- Check required fields and format compliance
- Verify WHO, WHAT, WHEN, WHERE, WHY, HOW elements
- Flag missing or inconsistent information
- Assess narrative quality
- Evaluate supporting evidence
- Assign compliance score (0-100)
- Set verification status: approved, needs_revision, rejected
- Identify issues by section, type, severity
- Provide recommendations for corrections

JSON OUTPUT SCHEMA:
{
    "verification_result": {
        "report_id": "string",
        "verification_timestamp": "string (ISO 8601 date-time format)",
        "is_compliant": "boolean",
        "compliance_score": "number (optional)",
        "verification_status": "string (approved, needs_revision, rejected)",
        "ready_for_submission": "boolean"
    },
    "fincen_requirements": {
        "required_fields_present": "boolean",
        "format_compliance": "boolean",
        "narrative_quality": "string (excellent, good, adequate, inadequate)",
        "supporting_evidence_sufficient": "boolean (optional)"
    },
    "issues": [
        {
            "section": "string",
            "issue_type": "string (missing_information, format_error, inconsistency, insufficient_detail)",
            "description": "string",
            "severity": "string (critical, major, minor)",
            "recommendation": "string (optional)"
        }
    ],
    "llm_verification": {
        "completeness_assessment": "string",
        "accuracy_assessment": "string",
        "consistency_check": "string (optional)",
        "overall_quality": "string (excellent, good, adequate, inadequate)"
    },
    "verification_summary": "string"
}
"""

class ComplianceVerificationAgent(BaseAgent):
    """Agent for verifying SAR report compliance with FinCEN requirements."""
    
    def __init__(self, client):
        """Initialize the compliance verification agent.
        
        Args:
            client: API client for model access
            model: Model identifier to use
        """
        super().__init__(client)
        self.system_prompt = SYSTEM_PROMPT
    
    def run(self, sar_report):
        """Verify SAR report compliance against FinCEN requirements.
        
        Args:
            sar_report: SAR report generated by the SAR Generation Agent
            
        Returns:
            Verification results with compliance assessment and issues
        """
        return super().run(sar_report)
